### ISSUE TITLE
Hook huh.exporter.event.modifyfieldvalue dows not work as expected

### ISSUE THREAD

**Issue by cmette** [heimrichhannot/contao-exporter-bundle#8]
I am trying to use the hook **huh.exporter.event.modifyfieldvalue** but it is not working **as expected**. I am using the EventSubscriber pattern with Symfony 4.3 and Contao 4.9.22. 

```
class HuhExporterEventModifyFieldValue implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        // return the subscribed events, their methods and priorities
        return [
            ModifyFieldValueEvent::NAME => 'onEvent'
        ];
    }

    public function onEvent(ModifyFieldValueEvent &$event)
    {
        $row = $event->getRow();
        $row['tl_user.name'] = '0';
        $event->setRow($row);
    }
}

```
The function is called correctly, but this has no effect on the spreadsheet. The exported spreadsheet is not modified at any time.

Do you have any suggestions?

With kind regards!

**Comment by koertho** [comment]
@Defcon0 This shouldn't have an impact.

**Comment by Defcon0** [comment]
I know, just curious

**Comment by Defcon0** [comment]
Ah, you just used the wrong method for proagating back to the event class:

https://github.com/heimrichhannot/contao-exporter-bundle/blob/master/src/Exporter/AbstractPhpSpreadsheetExporter.php#L99

`value` is the property you like to adjust, not row ;-) Because you registered a `ModifyField*Value*` subscriber ;-)
